INSERT INTO theme_stats (institution, ranking, category, tema, subtema, percentage, num_questions, cor, cor_hex, source_file)
VALUES
    ('FAMERP', 1, 'area', 'Emergências Cirúrgicas', NULL, 10.0, 40, 'vermelho', '#EF4444', 'FAMERP.pdf'),
    ('FAMERP', 2, 'area', 'Saúde do Trabalhador', NULL, 5.5, 22, 'vermelho', '#EF4444', 'FAMERP.pdf'),
    ('FAMERP', 3, 'area', 'Gastroenterologia', NULL, 4.75, 19, 'vermelho', '#EF4444', 'FAMERP.pdf'),
    ('FAMERP', 4, 'area', 'Ginecologia Geral', NULL, 4.5, 18, 'vermelho', '#EF4444', 'FAMERP.pdf'),
    ('FAMERP', 5, 'area', 'Neonatologia', NULL, 4.25, 17, 'vermelho', '#EF4444', 'FAMERP.pdf'),
    ('FAMERP', 1, 'tema', 'Trauma', NULL, 6.0, 24, 'vermelho', '#EF4444', 'FAMERP.pdf'),
    ('FAMERP', 2, 'tema', 'Parto', NULL, 3.5, 14, 'vermelho', '#EF4444', 'FAMERP.pdf'),
    ('FAMERP', 3, 'tema', 'Declaração de Óbito', NULL, 2.75, 11, 'vermelho', '#EF4444', 'FAMERP.pdf'),
    ('FAMERP', 4, 'tema', 'Abdome agudo', NULL, 2.25, 9, 'vermelho', '#EF4444', 'FAMERP.pdf'),
    ('FAMERP', 5, 'tema', 'Endocrinologia ginecológica', NULL, 2.25, 9, 'vermelho', '#EF4444', 'FAMERP.pdf'),
    ('FAMERP', 6, 'tema', 'Doenças ocupacionais', NULL, 2.0, 8, 'vermelho', '#EF4444', 'FAMERP.pdf'),
    ('FAMERP', 7, 'tema', 'Pâncreas', NULL, 2.0, 8, 'vermelho', '#EF4444', 'FAMERP.pdf'),
    ('FAMERP', 8, 'tema', 'Notificação', NULL, 1.75, 7, 'vermelho', '#EF4444', 'FAMERP.pdf'),
    ('FAMERP', 9, 'tema', 'Infecções congênitas', NULL, 1.75, 7, 'vermelho', '#EF4444', 'FAMERP.pdf'),
    ('FAMERP', 10, 'tema', 'Hipertensão arterial sistêmica (HAS)', NULL, 1.75, 7, 'vermelho', '#EF4444', 'FAMERP.pdf'),
    ('FAMERP', 1, 'subtema', 'Trauma', 'Abordagem inicial', 2.27, 9, 'vermelho', '#EF4444', 'FAMERP.pdf'),
    ('FAMERP', 2, 'subtema', 'Trauma', 'Trauma de abdome', 1.77, 7, 'vermelho', '#EF4444', 'FAMERP.pdf'),
    ('FAMERP', 3, 'subtema', 'Notificação', 'Lista nacional de agravos de notificação compulsória', 1.52, 6, 'vermelho', '#EF4444', 'FAMERP.pdf'),
    ('FAMERP', 4, 'subtema', 'Pâncreas', 'Pancreatite aguda', 1.52, 6, 'vermelho', '#EF4444', 'FAMERP.pdf'),
    ('FAMERP', 5, 'subtema', 'Sofrimento fetal agudo', 'Cardiotocografia e perfil biofísico fetal', 1.52, 6, 'vermelho', '#EF4444', 'FAMERP.pdf'),
    ('FAMERP', 6, 'subtema', 'Declaração de Óbito', 'Como preencher', 1.52, 6, 'vermelho', '#EF4444', 'FAMERP.pdf'),
    ('FAMERP', 7, 'subtema', 'Normas da saúde do trabalhador', 'Regulamentadoras (NR)', 1.52, 6, 'vermelho', '#EF4444', 'FAMERP.pdf'),
    ('FAMERP', 8, 'subtema', 'Hipertensão arterial sistêmica (HAS)', 'Classificação e Tratamento', 1.26, 5, 'laranja', '#F97316', 'FAMERP.pdf'),
    ('FAMERP', 9, 'subtema', 'Câncer de colo uterino', 'Rastreamento e conduta nas lesões intraepiteliais cervicais', 1.26, 5, 'laranja', '#F97316', 'FAMERP.pdf'),
    ('FAMERP', 10, 'subtema', 'Lei 8.080 ou 8080', 'Princípios e diretrizes do SUS', 1.01, 4, 'laranja', '#F97316', 'FAMERP.pdf'),
    ('FAMERP', 11, 'subtema', 'Declaração de Óbito', 'Quem deve preencher', 1.01, 4, 'laranja', '#F97316', 'FAMERP.pdf'),
    ('FAMERP', 12, 'subtema', 'Abdome agudo', 'Colecistite aguda', 1.01, 4, 'laranja', '#F97316', 'FAMERP.pdf'),
    ('FAMERP', 13, 'subtema', 'Puerpério patológico', 'Distúrbios psiquiátricos, hemorragia e infecção', 1.01, 4, 'laranja', '#F97316', 'FAMERP.pdf'),
    ('FAMERP', 14, 'subtema', 'Validação de Testes de Diagnósticos', 'Cálculos', 1.01, 4, 'laranja', '#F97316', 'FAMERP.pdf'),
    ('FAMERP', 15, 'subtema', 'Medidas de associação', 'De associação em estudos intervencionistas', 1.01, 4, 'laranja', '#F97316', 'FAMERP.pdf'),
    ('FAMERP', 16, 'subtema', 'Endocrinologia ginecológica', 'Amenorreia', 1.01, 4, 'laranja', '#F97316', 'FAMERP.pdf'),
    ('FAMERP', 17, 'subtema', 'Parto', 'Amniorrexe prematura', 1.01, 4, 'laranja', '#F97316', 'FAMERP.pdf'),
    ('FAMERP', 18, 'subtema', 'Parto', 'Partograma', 1.01, 4, 'laranja', '#F97316', 'FAMERP.pdf'),
    ('FAMERP', 19, 'subtema', 'Obstrução intestinal', 'Alta', 0.76, 3, 'amarelo', '#EAB308', 'FAMERP.pdf'),
    ('FAMERP', 20, 'subtema', 'Calendário Vacinal', 'Calendário da criança', 0.76, 3, 'amarelo', '#EAB308', 'FAMERP.pdf'),
    ('FAMERP', 21, 'subtema', 'Infecções congênitas', 'Sífilis congênita no RN', 0.76, 3, 'amarelo', '#EAB308', 'FAMERP.pdf'),
    ('FAMERP', 22, 'subtema', 'Doenças da paratireoide', 'Hiperparatireoidismo e hipercalcemia', 0.76, 3, 'amarelo', '#EAB308', 'FAMERP.pdf')
ON CONFLICT (institution, category, tema, subtema) DO UPDATE SET
    ranking = EXCLUDED.ranking,
    percentage = EXCLUDED.percentage,
    num_questions = EXCLUDED.num_questions,
    cor = EXCLUDED.cor,
    cor_hex = EXCLUDED.cor_hex;
